version: "3"
services:
  frontend:
    build: frontend
    #container_name: frontend_C
    env_file: .env
    ports:
      - 8081:5173
    restart: unless-stopped
    # stdin_open: true
    # tty: true

  backend:
    build: Server-Node
    #container_name: backend_node_C
    env_file: .env
    ports:
      - 8080:4000
    restart: unless-stopped

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
    ports:
      - 3306:3306
  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8081:80
  #   environment:
  #     - PMA_ARBITRARY=1
